language: java
notifications:
  hipchat:
    rooms:
      secure: Np4rUmYYr2FJ1eZIZXK+rF1AjAua/BpGFpDiifARfZVCHXnSCvaof2HRsQYpSHb2Cy9ZfVFMv8CHTZOtweBCDSty/9mPbTFLS6NUmlGJ75EHM/PrOJij1gGrsIv0+la7Nw0uReyLWiTlfeEG+/K7r2zJU8QILFVEma2eEM0AtQA7WY7ILDDt70INomnLVT7AAgckHVJVj+wvqCd5PLlp0x7ZsUXKW38mwdzARPA702vTx7SkDjjuDEvAShV/jCBXhDLZsbZI2fPA1dePNVh+Htl/wYshfEmW2g8mLjqX5VkWZyvIfyvyoFMPwbY9qFL5w5Z41Pi+TL0p3SKoaIBQ7saOZfTyWMnIB54hACrdB/okwEOtF5IWB4bmofZulSsR3GssgidA+xKmFvysONtuSeiwghmSkVnXZdoqdnCxwoZVokwOHIwr6lKi80aXVSQugDGoln8BhFG+RGx88rgL1jDSVs9tML35wjCfJCjR9WTA9HpLyQKYEDRkmaqtmkNKKWTmvX2UdyDMnjeddLOkOHiHaQCoKiXlezBi8I9HHYpUeAz5VeIBpFY/Fr0mmWtTs3LNdJCoTt7msawuTH0K/CKqdAB28hwX7GOULnJPhpmxZl5S8srqcCTrKJeZ3zItjTbrhjeTcMzp2CmGBLXtEuI/llN6Je0fepACJFUZwBo=
deploy:
  provider: releases
  api_key:
    secure: KFaoT8WzvT1sIwf4OpKF2OXYCp112WKsn97sPRuEt76zaXGuFjIBNqO6e2mqoaARhORIP88SY5ztJRbFmQieD8PvwMiy3+5gO5OEl6T12EEM/yrlCwfSysh+HC0MKmOdjKq+tS2j9pMj/b8QF7o1KZyIQiOczIjt+on3gn++vKZeqanDshPOyDiigVKOjG/FsZbO9SD50JlLnNMux5Z9+F9A8h3wSL9+L6ilpao7+KhUnbG2/Hqqf0y0/8+se0v2Sx2Vj8n2pXpp9vCfTLPSJGWCYlwQVYV/hDzc5RCjC6+rQyUvU1DkX0pzZYVdqG5VpbFZm84hPOBdmQEl3/AHxFdKtERQOe7eb5HDvqtfqHWlETG47BHUMSaHbSBP7GansdXRLF74Wlosi3e+QeDM8hLkA8HZiyz1qiyeVByQU+hZqbdbjqRXeizxrJUo8/5Pc2UQVHTmUTpd7glHGxRoBm9cgkTp6SNUE/mX+595pG8/DGvH5t0AWyynuGDFRLRzrmAKfgnzztzUoOEmEgBM3qI9MyZXhR+V6/z3XmgfDTRk/PLM8nDsagpCIwfTNyEUq78J7WwWSf3zUURY642/koVjpj5+YGUz9vNnFRnegyYGuCAFnqqXFmdQ5AO8zHQwsWNdpWZ0mmu71hS0zgBtc5u5wpmAnsp4sJWhsnWGwOw=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-hashicorp-vault-plugin
