language: java
notifications:
  hipchat:
    rooms:
      secure: Np4rUmYYr2FJ1eZIZXK+rF1AjAua/BpGFpDiifARfZVCHXnSCvaof2HRsQYpSHb2Cy9ZfVFMv8CHTZOtweBCDSty/9mPbTFLS6NUmlGJ75EHM/PrOJij1gGrsIv0+la7Nw0uReyLWiTlfeEG+/K7r2zJU8QILFVEma2eEM0AtQA7WY7ILDDt70INomnLVT7AAgckHVJVj+wvqCd5PLlp0x7ZsUXKW38mwdzARPA702vTx7SkDjjuDEvAShV/jCBXhDLZsbZI2fPA1dePNVh+Htl/wYshfEmW2g8mLjqX5VkWZyvIfyvyoFMPwbY9qFL5w5Z41Pi+TL0p3SKoaIBQ7saOZfTyWMnIB54hACrdB/okwEOtF5IWB4bmofZulSsR3GssgidA+xKmFvysONtuSeiwghmSkVnXZdoqdnCxwoZVokwOHIwr6lKi80aXVSQugDGoln8BhFG+RGx88rgL1jDSVs9tML35wjCfJCjR9WTA9HpLyQKYEDRkmaqtmkNKKWTmvX2UdyDMnjeddLOkOHiHaQCoKiXlezBi8I9HHYpUeAz5VeIBpFY/Fr0mmWtTs3LNdJCoTt7msawuTH0K/CKqdAB28hwX7GOULnJPhpmxZl5S8srqcCTrKJeZ3zItjTbrhjeTcMzp2CmGBLXtEuI/llN6Je0fepACJFUZwBo=
deploy:
  provider: releases
  api_key:
    secure: PqIsBHJPwySENaK0MIdK33RmIHbXB9gtNwh4J9RkEC3nsfox76+9mHEjR8OHEte6EDGwV3b1sjAr4xZ55zG3h/gYiZqk7gc8JfVWpzr88LUH/5YzrUJHsC//poeVGB4tGpnYck8Qj1nFo+kk7/f4lcrkNEvpOGCLJtZyW2xL4uN88YDugd1SgY3rtZ7q1vK3Rb3RHrAxwlg/lTDYqvgDR35uuwkAfLS88aW5JVCYcgPshMVLG1tEVr4sCJGpqXd3PVtNclETwt1FKh7CoIafjfos3INdKi2kRQAW3PdeDbrAH0tII+hxnhKH2fV/JOTgkLHgQz86L4DCUFCbPBn0k2YRCEYdFoAsr9An8J57guPgevgSzbnugmihUcpCF2nY5x9D3GV3dTbZ2R+F6G/n/0Fo1dJfbCnQxFSd1TekdKCL+5iic265c7MTgIXlagTjUG3nmURbFIfsYqq7jRivXZM0zhft1xNvkS7bkENXe3CG4H9FpGuCadK8EBjMEf1m69s5euk5YhgiqwZUl5Ey0PtjpLhUlSspZrX9lkkjNrFoC6VnDjHSDTfQpYnmEFje59Twfe5kgkOlA0/kjZk0gbcUCEnddCt49tSQuwH4eICkZ8y4ukLqUUbUAgCetbnSoRhYrmvd0DsZSjN92LZvHjlBd7VJG7/fLIa3dv5eR+I=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-hashicorp-vault-plugin
