language: java
notifications:
  slack:
    secure: HBq4AW+ssUyA8ZOjVL0YbsUxWqfRqJwZOmG2jOGKKAMUJU6MhOi/Lrxd0R60mlCQvDFtsYdx6BOqaiaByUOGi0Y2+/QLnYsTXejsfT2Ez+1xeV0YDa2msDJ3nm81eHSu0WncWwZVHpUk7GnPSEX9agWnRknWlKXrqw3WLuCnkF2gkB3hERCz+RFqoaEwpBY3szfs2ObwT14ZjjjD5YIJt/jxytnIdGIdMvhDMVJiuhy3CLjuAUWbvfNWqZghWEXAtOM2KliP7rcapXReR5+XL1qYTiYq0w9fMGn87JUX4WuzQYRfVSe+O4OtAIp/CgkTkx4MyjhcmbMhAy/Jr8yWa3W6vKboCckq2wV2wo/Lf9dxWSOOA5v5yeCr+8lJmPsggJW5ZHb6rgeSQtsr48iykYot4IUi3SBsxuQIsKgnqgO46xgy/Z0CfnLRG71LvQhKCNOOO6BElnzvbOaeo47/Sn6Q0oC+f6C7cnGi5y0hdR/dPAJmZZReH3++s/OQ4Wwws4u+X9U19DiXYdwHmvJBY1T3zMNK5ctU9tEs0LkDjJqW7aP6dTL1iLISI/R5B0tTp3RuoBojDFECX0gYKLNdd1KFHnmy4g7068Tx80p8E8DXRxLY+hA47gLXhZGvzpZkMVZYvkVglx0KvOnd8Znb2qua0+DE9WeC4BtACoQcLbE=
deploy:
  provider: releases
  api_key:
    secure: PqIsBHJPwySENaK0MIdK33RmIHbXB9gtNwh4J9RkEC3nsfox76+9mHEjR8OHEte6EDGwV3b1sjAr4xZ55zG3h/gYiZqk7gc8JfVWpzr88LUH/5YzrUJHsC//poeVGB4tGpnYck8Qj1nFo+kk7/f4lcrkNEvpOGCLJtZyW2xL4uN88YDugd1SgY3rtZ7q1vK3Rb3RHrAxwlg/lTDYqvgDR35uuwkAfLS88aW5JVCYcgPshMVLG1tEVr4sCJGpqXd3PVtNclETwt1FKh7CoIafjfos3INdKi2kRQAW3PdeDbrAH0tII+hxnhKH2fV/JOTgkLHgQz86L4DCUFCbPBn0k2YRCEYdFoAsr9An8J57guPgevgSzbnugmihUcpCF2nY5x9D3GV3dTbZ2R+F6G/n/0Fo1dJfbCnQxFSd1TekdKCL+5iic265c7MTgIXlagTjUG3nmURbFIfsYqq7jRivXZM0zhft1xNvkS7bkENXe3CG4H9FpGuCadK8EBjMEf1m69s5euk5YhgiqwZUl5Ey0PtjpLhUlSspZrX9lkkjNrFoC6VnDjHSDTfQpYnmEFje59Twfe5kgkOlA0/kjZk0gbcUCEnddCt49tSQuwH4eICkZ8y4ukLqUUbUAgCetbnSoRhYrmvd0DsZSjN92LZvHjlBd7VJG7/fLIa3dv5eR+I=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-hashicorp-vault-plugin
